### PR TITLE
version 1

### PR DESCRIPTION
**Pull request by Darkflame72**
Add data classes for all responses
Add auto formatting, testing and code scanning
Add documentation

### CODE REVIEW

**Comment by Darkflame72** [comment]
I need to write better and more thorough docstrings

**Comment by Darkflame72** [comment]
If everything works then this is ready to merge

**Comment by AjayACST** [comment]
This will be ready to merge once the docstring for the player model is finished.

**Comment by Darkflame72** [comment]
Well breaking is a now certain as I just renamed the main class

**Comment by Darkflame72** [comment]
Feature wise this is done, cleanup for docs and docstrings is the last thing needed to be fixed

**Comment by Darkflame72** [comment]
@AjayACST is this ready to merge?

**Pull request merged**
