### PR TITLE
V1.1.0

### PR DESCRIPTION
**Pull request by Darkflame72**
Move to pydantic model creation

### CODE REVIEW

**Comment by Darkflame72** [comment]
Closes #248

**Comment by Darkflame72** [comment]
@duhby is there any specific data you want inside of stats? Currently we just have stuff for bedwars like number of kills, games etc

**Comment by duhby** [comment]
> @duhby is there any specific data you want inside of stats? Currently we just have stuff for bedwars like number of kills, games etc

Yeah I'll list a few here (probably shouldn't add *all* of these but just as an example):
- Star
- Kills
- Final Kills
- Deaths
- Final Deaths
- Kill/Death Ratio
- Beds Broken
- Beds Lost
- Beds Broken/Beds Lost Ratio
- Final Kills/Deaths Ratio
- Coins
- Wins
- Winstreak
- Win/Loss Ratio
- Wins
- Losses
- Games
- etc.

In the future you could also add support for some of these stats (some aren't available or not applicable) like Solos, Doubles, Threes, Fours, 4v4, and dreams but no one really cares about dreams at this point.
I can't really think of anything else you would want to add inside of bedwars, but there are other gamemodes you could add in the future like SkyWars and Duels to name a few popular ones.

**Comment by Darkflame72** [comment]
That sounds good, I am currently building all the models for each stats so that would be for all the other game modes as well. I will make sure all of these are in there and post them all here once they are done.

**Comment by Darkflame72** [comment]
All the data for bedwars should now be in there and I will add the other stats as well

**Comment by Darkflame72** [comment]
@AjayACST can you please review?

**Pull request merged**
