### PR TITLE
Add new "Invalid API key" exception

### PR DESCRIPTION
**Pull request by aiexz**
Added new exceptions and corrected a few typos

### CODE REVIEW

**Comment by Darkflame72** [comment]
could you please make sure all of your code is formatted using black and then I will merge

**Comment by aiexz** [comment]
I am using the VS code with black formatting there. Is that enough?

**Comment by Darkflame72** [comment]
ok looks all good I will merge and close now

**Comment by Darkflame72** [comment]
@all-contributors please add @aiexz for code

**Pull request merged**
